services:
  web:
    build:
      context: ./frontend
    expose:
      - "5173"
    ports:
      - "5173:5173"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    extra_hosts:
      - host.docker.internal:host-gateway
      - mongodb:host-gateway
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: knitting-utils
    ports:
      - 27018:27017
    volumes:
      - ./mongodb_data:/data/db
